# Generated by Django 3.1.1 on 2021-04-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20210423_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='bookcover',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userbook',
            name='bookfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
